// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMS_klbtJR6uQ0lQfvyUPa_BoS_hvKTEQ',
    appId: '1:1080654449163:web:5f553e4143191b6d8e550e',
    messagingSenderId: '1080654449163',
    projectId: 'jawara-6ded8',
    authDomain: 'jawara-6ded8.firebaseapp.com',
    storageBucket: 'jawara-6ded8.firebasestorage.app',
    measurementId: 'G-H234K6MBKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYhstLsxK_1378cHZtQBUPINy_G1ZQTJ4',
    appId: '1:1080654449163:android:f4564bae2587e20c8e550e',
    messagingSenderId: '1080654449163',
    projectId: 'jawara-6ded8',
    storageBucket: 'jawara-6ded8.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Rdxrf086e9B7MaZOy00ZrxatwI9S5NQ',
    appId: '1:1080654449163:ios:b949f1e453a71fae8e550e',
    messagingSenderId: '1080654449163',
    projectId: 'jawara-6ded8',
    storageBucket: 'jawara-6ded8.firebasestorage.app',
    iosBundleId: 'anabellatus.id.jawaraMobile',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Rdxrf086e9B7MaZOy00ZrxatwI9S5NQ',
    appId: '1:1080654449163:ios:b949f1e453a71fae8e550e',
    messagingSenderId: '1080654449163',
    projectId: 'jawara-6ded8',
    storageBucket: 'jawara-6ded8.firebasestorage.app',
    iosBundleId: 'anabellatus.id.jawaraMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMS_klbtJR6uQ0lQfvyUPa_BoS_hvKTEQ',
    appId: '1:1080654449163:web:fbf08b5a03857eb68e550e',
    messagingSenderId: '1080654449163',
    projectId: 'jawara-6ded8',
    authDomain: 'jawara-6ded8.firebaseapp.com',
    storageBucket: 'jawara-6ded8.firebasestorage.app',
    measurementId: 'G-2H34BC7TRS',
  );
}
